// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwzazfzrsxbngfxqyeug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3emF6Znpyc3hibmdmeHF5ZXVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDUzNzAsImV4cCI6MjA1OTk4MTM3MH0.eH7UyGsIMQsl4QdwyQ4D3YvHZdiGg54rMy5aZH_BYEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);